build: false
environment:
  matrix:
  - PHP_VERSION: 5.6.17
    BUILD_PLATFORM: x86
  - PHP_VERSION: 5.5.31
    BUILD_PLATFORM: x86
  - PHP_VERSION: 7.0.2
    BUILD_PLATFORM: x86
  - PHP_VERSION: 5.6.17
    BUILD_PLATFORM: x64
  - PHP_VERSION: 5.5.31
    BUILD_PLATFORM: x64
  - PHP_VERSION: 7.0.2
    BUILD_PLATFORM: x64
  PHP_VC: 11
  PHP_SDK: c:\projects\php-sdk
  PHP_DEVPACK: c:\projects\php-devpack
  NO_INTERACTION: 1

os: Windows Server 2012
clone_folder: c:\projects\tideways

init:
    - SET PATH=c:\php;c:\projects\php-devpack;%PATH%
    - SET PHP=1
    - SET ANSICON=121x90 (121x90)

install:
  - echo Setting PHP version...
  - ps: >-
      If ($env:PHP_VERSION -Match "latest") {
        Start-FileDownload 'http://windows.php.net/downloads/releases/sha1sum.txt'
        $env:PHP_VERSION=type sha1sum.txt | where { $_ -match "php-(5\.6\.\d+)-src" } | foreach { $matches[1] }
        $env:version='{build}-$(PHP_VERSION)'
      } Else {
        $env:version='{build}-$(PHP_VERSION)'
      }
  - echo Initializing Build...
  - cd %APPVEYOR_BUILD_FOLDER%
  - echo Preparing Tideways win32 build...
  - echo Downloading PHP source code [%PHP_VERSION%]
  - ps: (new-object net.webclient).DownloadFile('http://windows.php.net/downloads/releases/php-' + ${env:PHP_VERSION} + '-Win32-VC' + ${env:PHP_VC} + '-' + ${env:BUILD_PLATFORM} + '.zip', ${env:APPVEYOR_BUILD_FOLDER} + '\..\php.zip')
  - cd ..
  - 'mkdir php && mv php.zip php\php.zip && cd php'
  - 7z.exe x php.zip | FIND /V "ing  "
  - cd ..
  - echo Downloading PHP-SDK
  - mkdir php-sdk && cd php-sdk
  - ps: (new-object net.webclient).DownloadFile('http://windows.php.net/downloads/php-sdk/php-sdk-binary-tools-20110915.zip', ${env:APPVEYOR_BUILD_FOLDER} + '\..\php-sdk.zip')
  - '7z.exe x ..\php-sdk.zip | FIND /V "ing  "'
  - cd ..
  - echo Downloading PHP-Devel-Pack
  - ps: (new-object net.webclient).DownloadFile('http://windows.php.net/downloads/releases/php-devel-pack-' + ${env:PHP_VERSION} + '-Win32-VC' + ${env:PHP_VC} + '-' + ${env:BUILD_PLATFORM} + '.zip', ${env:APPVEYOR_BUILD_FOLDER} + '\..\php-dev.zip')
  - 7z.exe x php-dev.zip | FIND /V "ing  "
  - mv php-%PHP_VERSION%-devel-VC11-%BUILD_PLATFORM% php-devpack
  - '"%VS110COMNTOOLS%\VsDevCmd" %BUILD_PLATFORM%'
  - echo Building PHP [%PHP_VERSION%]
  - '%PHP_SDK%\bin\phpsdk_setvars'
  - 'cd %APPVEYOR_BUILD_FOLDER%\..\php'
  - 'echo extension_dir=%APPVEYOR_BUILD_FOLDER%\..\php\ext > php.ini'
  - 'echo extension=%APPVEYOR_BUILD_FOLDER%\Release_TS\php_tideways.dll >> php.ini'
  - 'echo extension=php_pdo_sqlite.dll >> php.ini'
  - 'set PATH=%cd%;%PATH%'
  - cd c:\projects\tideways
  - appveyor DownloadFile https://phar.phpunit.de/phpunit-4.8.15.phar

test_script:
    - cd c:\projects\tideways
    - Setlocal EnableDelayedExpansion
    - echo "phpize"
    - c:\projects\php-devpack\phpize --clean
    - echo "./configure"
    - configure --enable-tideways=shared
    - echo "make"
    - nmake 2> compile-errors.log 1>compile.log
    - echo "make test"
    - php phpunit-4.8.15.phar tests/

on_failure:
  - 'dir'
  - 'type compile-errors.log'
  - 'type compile.log'

artifacts:
  - path: Release_TS\php_tideways.dll
